--- 
- name: sync project from github webhook
  hosts: all
  collections:
    - ansible.tower
  tasks:
    - name: retrieve all projects from Tower
      ansible.tower.tower_export:
        all: true
        tower_host: https://localhost
        tower_username: "admin"
        tower_password: "redhat"
        validate_certs: false
      register: tower_project_list

    - name: debug output
      debug:
        var: tower_project_list
